trigger:
  branches:
    include:
    - main
    - feature/*
    - bug/*
  paths:
    exclude:
    - README.md

pool:
  name: sphere-linux-pool

variables:
- name: major
  value: 1
- name: minor
  value: 0
- name: patch
  value: $(Build.BuildID)
- name: rev
  value: 'rev-$(git rev-parse --short HEAD)'

stages:
  - stage: 'SANDBOX'
    displayName: 'SANDBOX'
    jobs:
      - job: execute_create_alert_script
        steps:
          - template: put_admin_template.yml
            parameters:
              stage: 'sandbox'
              region: 'eu-west-1'
              service_connection: 'AWS-Sandbox-AssumeRole-SC'
              
              steps:
                - task: ManualValidation@0
            timeoutInMinutes: 720 # task times out in 12 hours
            inputs:
              instructions: |
                Please validate the rollback for $(System.StageDisplayName).
              onTimeout: reject
      - job: RollbackApproval
        dependsOn:
          - Rollback

  - stage: 'DEV'
    displayName: 'DEV'
    jobs:
      - job: execute_create_admin_script
        steps:
          - template: put_admin_template.yml
            parameters:
              stage: 'dev'
              region: 'eu-west-1'
              service_connection: 'DEV-SRE'
              
              steps:
                - task: ManualValidation@0
                  timeoutInMinutes: 720 # task times out in 12 hours
                  inputs:
              instructions: |
                Please validate the rollback for $(System.StageDisplayName).
              onTimeout: reject
      - job: RollbackApproval
        dependsOn:
          - Rollback


  - stage: 'STG'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'STG'
    dependsOn: DEV
    jobs:
      - job: execute_create_admin_script
        steps:
          - template: put_admin_template.yml
            parameters:
              stage: 'stg'
              region: 'eu-west-1'
              service_connection: 'STG-SRE'
              
              steps:
                - task: ManualValidation@0
                  timeoutInMinutes: 720 # task times out in 12 hours
                  inputs:
              instructions: |
                Please validate the rollback for $(System.StageDisplayName).
              onTimeout: reject
      - job: RollbackApproval
        dependsOn:
          - Rollback


  - stage: 'PROD'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'PROD'
    dependsOn: STG
    jobs:
      - job: execute_create_admin_script
        steps:
          - template: put_admin_template.yml
            parameters:
              stage: 'prod'
              region: 'eu-west-1'
              service_connection: 'PRD-SRE'
